app/paccoProject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'paccoProject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^paccotest/', include('paccotest.urls', namespace="paccotest")),
    url(r'^admin/', include(admin.site.urls)),
)

app/paccotest/urls.py
from django.conf.urls import patterns, url

from paccotest import views


urlpatterns = patterns('',
    # ex: /polls/
    url(r'^opening/$', views.opening, name='opening'),
    url(r'^intro/(?P<lg>[a-z]+)$', views.intro, name='intro'),
    url(r'^gpsPositionForm/$', views.gpsPositionForm, name='gpsPositionForm'),
    url(r'^questionnaireForm/$', views.questionnaireForm, name='questionnaireForm'),
    url(r'^probesForm/$', views.probesForm, name='probesForm'),
    url(r'^complete/$', views.complete, name='complete'),
    url(r'^uploadToServer/$', views.uploadToServer, name='uploadToServer'),
    url(r'^calibrate/$', views.calibrateMenu, name='calibrateMenu'),
    url(r'^calibrate/(?P<probeType>[0-9]+)/$', views.calibrate, name='calibrate'),


    #Ajax
    url(r'^gpsPositionForm/gpsPosition/$', views.gpsPosition, name='gpsPosition'),
    #url(r'^probesForm/(?P<probeName>[a-zA-Z]+)/probeMeasure/$', views.probeMeasure, name='probeMeasure'),  #Ex: http://127.0.0.1:8000/paccotest/probeMeasure/ph/
    url(r'^probesForm/(?P<probeChannel>[0-9]+)/probeMeasure/$', views.probeMeasure, name='probeMeasure'),  #Ex: http://127.0.0.1:8000/paccotest/probeMeasure/ph/
    url(r'^update/$', views.update, name='update'),  #Ex: http://127.0.0.1:8000/paccotest/probeMeasure/ph/
    url(r'^uploadToServer/uploadToServerClick/$', views.uploadToServerClick, name='uploadToServerClick'),  #Ex: http://127.0.0.1:8000/paccotest/probeMeasure/ph/
    url(r'^uploadToServer/doShutdown/$', views.doShutdown, name='doShutdown'),  #Ex: http://127.0.0.1:8000/paccotest/probeMeasure/ph/
    url(r'^complete/doShutdown/$', views.doShutdown, name='doShutdown'),  #Ex: http://127.0.0.1:8000/paccotest/probeMeasure/ph/
    url(r'^complete/doPrint/(?P<datas>.+)$', views.doPrint, name='doPrint'),
    url(r'^calibrate/(?P<probeType>[0-9]+)/(?P<stepID>[0-9]+)/$', views.calibrateMeasure, name='calibrateMeasure'),
)

app/paccotest/forms.py
from django import forms
from paccotest.models import Survey, Answer, Question, ProbeMeasure
from django.forms.formsets import formset_factory
from django.forms.models import inlineformset_factory

class GPSMeasureForm(forms.ModelForm):
    #Will override the utc from Survey Model
    #Needed to specify Date Format
    #utc = forms.DateField(widget=forms.DateInput(format = '%d/%m/%Y'), input_formats=('%d/%m/%Y',))

    class Meta:
        model = Survey
        fields = ['latitude', 'longitude', 'elevation', 'utc', ]
        #exclude = ('utc',)

    def __init__(self, *args, **kwargs):
        super(GPSMeasureForm, self).__init__(*args, **kwargs)

        self.fields['latitude'].widget = forms.HiddenInput()
        self.fields['longitude'].widget = forms.HiddenInput()
        self.fields['elevation'].widget = forms.HiddenInput()
        self.fields['utc'].widget = forms.HiddenInput()

class ProbeMeasureForm(forms.ModelForm):

    class Meta:
        model = ProbeMeasure
        fields = ['probeType', 'measure',]

    def __init__(self, *args, **kwargs):
        super(ProbeMeasureForm, self).__init__(*args, **kwargs)

        self.fields['probeType'].widget = forms.HiddenInput()
        self.fields['measure'].widget = forms.HiddenInput()
#

# UserAnswerFormSet = formset_factory(UserAnswerForm)
# formset = UserAnswerFormSet()
# for form in foclass UserAnswerForm(forms.Form)
#     question_id = forms.IntegerField()
#     answer_id = forms.IntegerField()rmset:
#     print(form.as_table())
#    inlineformset_factory(Answer, Question.answers.through)

# class QuestionForm(forms.ModelForm):
#
#     #http://mounirmesselmeni.github.io/2013/11/25/django-grouped-select-field/
#
#      answers = forms.ModelChoiceField(Answer.objects.all(), widget=forms.RadioSelect)
#
#     #  category = GroupedModelChoiceField(
#     #     label=_('Category'),
#     #     group_by_field='parent',
#     #     queryset=Category.objects.all(),
#     # )
#
#
#
#      class Meta:
#          model = Question
#
#      def __init__(self, *args, **kwargs):
#          super(QuestionForm, self).__init__(*args, **kwargs)


# class QuestionForm(forms.ModelFor
#     #http://chase-seibert.github.io/blog/2010/05/20/django-manytomanyfield-on-modelform-as-checkbox-widget.html
#     #http://stackoverflow.com/questions/2216974/django-modelform-for-many-to-many-fields
#
#     class Meta:
#         model = Question
#         fields = ('question_text',)
#
#     # Representing the many to many related field in Pizza
#     answers = forms.ModelChoiceField(queryset=Answer.objects.all(),  widget=forms.RadioSelect)
#
#     # def __init__(self, *args, **kwargs):
#     #     super(QuestionForm, self).__init__(*args, **kwargs)
#     #
#     #     self.fields["answers"].widget = forms.CheckboxSelectMultiple()
#     #     self.fields["answers"].queryset = Answer.objects.all()m):

app/paccotest/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django import forms
from django.utils.translation import ugettext as _
from django.utils.translation import activate as translationactivate
from django.utils.translation import get_language as translationget_language
from django.utils.translation import LANGUAGE_SESSION_KEY

from paccotest.models import Question, Probe, CalibrationMemo, WaterCategoriesValue
from paccotest.forms import GPSMeasureForm,ProbeMeasureForm
import json
import unicodedata

from paccotest.hardware.probesManager import GPSPosition, ProbesManager

# import the logging library
import logging

# Get an instance of a logger
logger = logging.getLogger(__name__)

class ProbesManagerFactory:
    @classmethod
    def make_realProbesManager(Class):
        #return Class.ProbesManagerReal()
        return globals()['ProbesManagerReal']()

    @classmethod
    def make_dummyProbesManager(Class):
        #return Class.ProbesManagerDummy()
        return globals()['ProbesManagerDummy']()


global IS_DEBUGGING
IS_DEBUGGING = True  #Set IS_DEBUGGING for RaspberryPI

if IS_DEBUGGING:
    from paccotest.hardware.probesManagerDummy import ProbesManagerDummy
    g_probesMananager = ProbesManagerFactory.make_dummyProbesManager();  #For Dummy Probes
else:
    from paccotest.hardware.probesManagerReal import ProbesManagerReal
    g_probesMananager = ProbesManagerFactory.make_realProbesManager();  #For Real Probes



# Create your views here.


# The Opening Page
def opening(request):
    g_probesMananager.allProbesToSleep()
    return render(request, 'paccotest/opening.html')

# The Intro Page
def intro(request,lg):
    request.session.clear()
    translationactivate(lg)
    request.session[LANGUAGE_SESSION_KEY] = lg
    return render(request, 'paccotest/intro.html')

# The form (hidden) for GPS Position
def gpsPositionForm(request):
    #http://stackoverflow.com/questions/14901680/how-to-do-a-multi-step-form-in-django
    #http://stackoverflow.com/questions/23285558/datetime-date2014-4-25-is-not-json-serializable-in-django

    initial={'gpsForm': request.session.get('gpsForm', None)}
    form = GPSMeasureForm(request.POST or None, initial=initial)

    if request.method == "POST":

        if form.is_valid():
            form.cleaned_data["utc"] = json.dumps(form.cleaned_data["utc"], cls = DateTimeEncoder)
            request.session['gpsForm'] = form.cleaned_data
            return HttpResponseRedirect(reverse('paccotest:questionnaireForm'))
        else:
            print "GpsForm not valid!"
            print form.errors.as_json()

    return render(request, 'paccotest/gpsPositionForm.html', {'form':form})


# Page of the survey
def questionnaireForm(request):

    initial={'questionnaireValues': request.session.get('questionnaireValues', None)}
    form = forms.Form(request.POST or None, initial=initial)
    #form = QuestionForm(request.POST or None, initial=initial)

    if request.method == 'POST':

        if form.is_valid():  #Useless!
            if 'questionnaireValues' not in request.session:
                 request.session['questionnaireValues']={}

            #Get values of the form
            #Key: QuestionID,   Value: AnswerID
            for i in request.POST:
                if i !=  "csrfmiddlewaretoken" and request.POST[i] != "> skip all Questions":    #TODO: Make it cleaner
                    #print 'I have been passed the following keys: ',i, ' and value:',request.POST[i]
                    request.session['questionnaireValues'][i] = request.POST[i]

            #print request.session['questionnaireValues']  #DEBUG
            return HttpResponseRedirect(reverse('paccotest:probesForm'))

    all_questions_list = Question.objects.all().filter(actif=True).order_by('order')
    firstTab = 1
    lastTab = all_questions_list.count() + 1
    context = {'all_questions': all_questions_list,'firstTab':firstTab,'lastTab':lastTab}
    return render(request, 'paccotest/questionnaireForm.html', context)


# Form for probes
def probesForm(request):
    all_probes_list = Probe.objects.all().order_by('order')
    lastTab = all_probes_list.count() + 1

    initial = {'probesValues': request.session.get('probesValues', None), 'all_probes': all_probes_list}
    form = forms.Form(request.POST or None, initial=initial)

    if request.method == 'POST':
        if form.is_valid():   #Useless!
            if 'probesValues' not in request.session:
                request.session['probesValues'] = {}

            # Get values of the form
            #Key: ProbeID,   Value: ProbeValue
            for i in request.POST:
                if i != "csrfmiddlewaretoken":  #TODO: Make it cleaner
                    #print 'I have been passed the following keys: ',i, ' and value:',request.POST[i]
                    request.session['probesValues'][i] = request.POST[i]
            print request.session['probesValues']  #DEBUG

            # if 'probesValues' not in request.session:
            #     request.session['probesValues'] = {}
            #
            #     for probe in all_probes_list:
            #         request.session['probesValues'][probe.id] = form.cleaned_data['probe' + str(probe.id)]
            #
            #     print request.session['probesValues']  #DEBUG


            return HttpResponseRedirect(reverse('paccotest:complete'))
    return render(request, 'paccotest/probesForm.html',
                  {'all_probes': all_probes_list, 'lastTab': lastTab, 'form': form})


from models import *  #TEMP

def complete(request):

    gpsValues = request.session['gpsForm']
    questionnaireValues = request.session['questionnaireValues']
    probesValues = request.session['probesValues']
    #print gpsValues
    #print questionnaireValues
    #print 'probesvalues===='
    #print probesValues  #DEBUG
    utc_formated = gpsValues["utc"][1:11]+' '+gpsValues["utc"][12:20]

    #Save GPS Values
    survey = Survey.objects.create(latitude = gpsValues["latitude"],
                                    longitude = gpsValues["longitude"],
                                    elevation = gpsValues["elevation"],
                                    utc = utc_formated
                                    )
    #Save Questionnaire
    for key in questionnaireValues:
        UserAnswer.objects.create(  survey = survey,
                                    answer=Answer.objects.get(id=questionnaireValues[key]),
                                    question=Question.objects.get(id=key))

    #Save Probes values
    for key in probesValues:
        ProbeMeasure.objects.create(  survey = survey,
                                    probeType=Probe.objects.get(id=key),
                                    measure=probesValues[key])


    #print(request.session.keys())   #DEBUG: Print all the keys

    #print(request.session.keys())
    #print(request.session['probesValues'])
    #all_WaterCategories_list = WaterCategories.objects.all()
    #all_surveyProbeMeasures_list = ProbeMeasure.objects.all().filter(survey = survey)

    all_WaterCategorie_list = WaterCategorie.objects.all().order_by('order')
    #probeMeasures_list = ProbeMeasure.objects.get(survey_id='61')

    waterCategorieGoodtoUse_list = []

    for waterCategorie in all_WaterCategorie_list:
        watercategorieOK = True

        #print waterCategorie.text
        #for probe in probeMeasures_list:
        probesValues = request.session['probesValues']
        #print probesValues
        for key in probesValues:
            probe = Probe.objects.get(id=key)
            if probe.criterable == True:
                #print key
                #item = WaterCategoriesValue.objects.get(waterCategorie=waterCategorie,probeType=probe.probeType_id)
                item = WaterCategoriesValue.objects.get(waterCategorie=waterCategorie,probeType=Probe.objects.get(id=key))
                #print 'max'+str(item.valueMax)
                #print 'min'+str(item.valueMin)
                #print 'prVal'+probesValues[key]
                if item.valueMax >= float(probesValues[key]) >= item.valueMin:
                    #print waterCategorie.text+': MAYBE'
                    pass
                else:
                    print waterCategorie.text+': NON'
                    watercategorieOK = False
                    break
        if watercategorieOK == True:
            print waterCategorie.text+': OUI'
            #waterCategorieGoodtoUse_list.append(waterCategorie.text)
            waterCategorieGoodtoUse_list.append(waterCategorie.id)


    #print 'eau bonne pour:'
    #print waterCategorieGoodtoUse_list
    #print ', '.join(waterCategorieGoodtoUse_list)
    waterCat_list = []
    waterCat_listinString = '0'
    for i in waterCategorieGoodtoUse_list:
	wcat= WaterCategorie.objects.get(pk=i)
        waterCat_list.append(wcat.text)
        waterCat_listinString = waterCat_listinString+'--'+str(wcat.id)
    context = {'SESSION': json.dumps(gpsValues)+ " ---- " +json.dumps(questionnaireValues)+ " ---- " + json.dumps(probesValues),'waterCategorieslist':waterCat_list,'waterCategories_listinString':waterCat_listinString}
    return render(request, 'paccotest/complete.html', context)



#--------------------- CRON ----------------------------------
#Called on startup, if the RPI is connected to internet
def uploadToServer(request):
    newSurveys = Survey.objects.filter(uploadedToServer=False)
    uploadedCount = newSurveys.count()


    print(uploadedCount);
    return render(request, 'paccotest/uploadToServer.html', {'newSurveysCount':uploadedCount})

###
# get Raspberry PI unique identifier
###
def getRPIserial():
  # Extract serial from cpuinfo file
  cpuserial = "0000000000000000"
  try:
    f = open('/proc/cpuinfo','r')
    for line in f:
      if line[0:6]=='Serial':
        cpuserial = line[10:26]
    f.close()
  except:
    cpuserial = "ERROR000000000"

  return cpuserial

app/paccotest/templates/paccotest/base.html
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Pacco-test | {% block titre %}{% endblock %}</title>

    {% load static %} <!-- New line -->
    <link rel="stylesheet" href="{% static 'jquery.mobile/jquery.mobile-1.4.4.min.css' %}" />
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script>
        //Disable "ajax loading" of the pages in jQueryMobile. Use standard HTTP behaviour
        //This script must be loaded before the jquery.mobile script
        $( document ).on( "mobileinit", function() {
            console.log("hello")
            $.extend( $.mobile , {
                //http://api.jquerymobile.com/global-config/
                ajaxEnabled: false
            });
        });
     </script>

    <!--<script src="{% static 'jquery.mobile/jquery.mobile-1.4.4.min.js' %}"></script>-->

   <link type="text/css" href="{% static 'css/main.css' %}?{% now 'U' %}" rel="stylesheet" />


    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/jquery-ui.min.js" %}"></script>
    <script src="{% static "js/angular.min.js" %}"></script>
    <script src="{% static "js/angular-animate.js" %}"></script>
    <script src="{% static "js/pacco-test.js" %}?{% now 'U' %}"></script>



    </head>
        <body ng-app="paccoApp">
        <div id="waitingscreen"><img src='{% static "img/waitingForPaccoTest.gif" %}' alt="waitingLogo" /></div>
        {% load i18n %}
            <div id="cadre">
                {% block content %}
                {% endblock %}
            </div>
        </body>
</html>

app/paccotest/templates/paccotest/calibrate.html
{% extends "paccotest/base.html" %}

{% load i18n %}
{% block content %}
<div ng-controller="TabController as tab">

	<p class="tabsNavigation">
	{% for step in allProbeSteps %}
		<span ng-class="{active:tab.isSet({{step.order}})}"><!--ng-click="tab.setTab({{probe.id}})"-->&nbsp;</span>
	{% endfor %}
		<span ng-class="{active:tab.isSet({{lastTab}})}"><!--ng-click="tab.setTab({{lastTab}})"-->&nbsp;</span>
	</p>
	{% for step in allProbeSteps %}

	    <div ng-controller="CalibrationController" ng-show="tab.isSet({{step.order}})" class="tabitem">


            <h2 style="position:fixed;top:3px;right:15px;display:block;text-align:right"><span class="bigger">{{ forloop.counter }}</span>/{{ allProbeSteps.count }}</h2>
            <span style="border:1px dotted black;position:fixed;top:3px;left:3px;padding:7px 15px;">{{ step.probeType.name }}</span>
	        <div ng-hide="myData.fromServer != null"></div>
            <div>
                 <h2 class="consigne" ng-hide="myData.fromServer != null"  style="position:fixed;bottom:0;left:1%;width:48%;height:200px;text-align:center;font-size:30px;display:table-cell;vertical-align:middle;">{{step.sentence}}</h2>
	            <a class="btn btnA" ng-hide="myData.fromServer != null" href ng-click="myData.doClick(item, $event,{{ step.probeType }},{{ step.id }});" style="-moz-border-radius: 15px;border-radius: 15px;position:fixed;bottom:10px;left:50%;text-decoration:none;color:black;font-size:29px;width:49%;padding-top:130px;height:170px;background-color:rgba(255,255,255,1);text-align:center;">{% trans "measure" %}</a>
	        </div>

	        <div ng-show="myData.fromServer != null">
                <div class="btnB" style="position:fixed;width:100%;left:20px;top:50px;font-size:23px;text-align:left;height:140px;padding-top:60px;"
             <p>Please make sure that the probe is dry and clean before next step.</p>
                </div>
                <input type="hidden" name="{{step.id}}" id="step{{step.id }}" value="{[{myData.fromServer}]}">
                {% if forloop.counter == allProbeSteps.count %}
	                 <a class="btnC"  href ng-click="tab.nextTab({{step.order}},{{ forloop.counter }});myData.doClick(item, $event,{{ step.probeType }},'0');" style="-moz-border-radius: 15px;border-radius: 15px;position:fixed;width:49%;left:50%;bottom:0;font-size:29px;text-align:center;height:80px;padding-top:40px;text-decoration:none;color:black;background-color:white;">{% trans "button-next" %}</a>
	            {% else %}
	                <a class="btnC"  href ng-click="tab.nextTab({{step.order}},{{ forloop.counter }});" style="-moz-border-radius: 15px;border-radius: 15px;position:fixed;width:49%;left:50%;bottom:0;font-size:29px;text-align:center;height:80px;padding-top:40px;text-decoration:none;color:black;background-color:white;">{% trans "button-next" %}</a>
                {% endif %}
            </div>

	    </div>
	{% endfor %}
        <div class="tabitem" ng-show="tab.isSet({{lastTab}})" class="ui-field-contain">
           <p>The {{step.probeType.name}} probe is now well calibrated.</p>
			<br />
            <a class="btn btnLarge btnChangePage" href="{% url 'paccotest:calibrateMenu' %}" style="margin:10px;">Back to calibration Menu</a>
           <button ng-click="shutdownAnswer.doShutdownClick(item, $event)" class="btn btnLarge">{% trans "Shutdown Paccotest" %}</button>
        </div>
</div>
{% endblock %}

app/paccotest/templates/paccotest/calibrateMenu.html
{% extends "paccotest/base.html" %}

{% load i18n %}
{% block content %}
Be careful, once you have clicked on one of the button below you'll have to go all the way to THE END of the process otherwise the probe won't be calibrated anymore.<br /><br />
{% for probe in all_probes %}
<a class="btn btnLarge btnChangePage" href="{% url 'paccotest:calibrate' probeType=probe.probeType.pk %}" style="margin:5px;width:190px;padding:15px;">{{probe.probeType.name}}<br /><span style="font-size:13px;">last calibration:<br />{{probe.date_calibration}}</span></a>
{% endfor %}
<span ng-controller="UploadToServerController">
    <button ng-click="shutdownAnswer.doShutdownClick(item, $event)" class="btn btnLarge" style="margin:5px;margin-left:240px;width:190px;padding:15px;"><br />SHUTDOWN<br /><br /></button>
</span>
{% endblock %}

app/paccotest/templates/paccotest/complete.html
{% extends "paccotest/base.html" %}
{% load i18n %}
{% block content %}
    <div ng-controller="UploadToServerController" style="text-align:center;">
        <h1>{% blocktrans %}Résultats Pacco-test{% endblocktrans %}</h1>
        <br />
        <p>
       {% if waterCategorieslist|length >= 1 %}
    {% for item in waterCategorieslist %}
        {% if forloop.counter == 1 %}
            {% blocktrans %}La meilleure utilisation de cette eau est pour :{% endblocktrans %}
            <strong>{{ item }}</strong>
            <br />
        {% elif forloop.counter == 2 %}
            <br />
            {% blocktrans %}Elle peut aussi être utilisée pour :{% endblocktrans %}
            <strong>{{ item }}</strong>{% if forloop.counter < waterCategorieslist|length %}, {% endif %}
        {% else %}
             <strong>{{ item }}</strong>{% if forloop.counter < waterCategorieslist|length %}, {% endif %}
        {% endif %}
    {% endfor %}
{% else %}
    {% blocktrans %}Cette eau ne devrait pas être utilisée.{% endblocktrans %}<br />
{%endif %}
            </p>
            <br />
            <h2>{% blocktrans %}Merci de votre participation{% endblocktrans %}</h2>

        <br />
       <button ng-click="myData.doPrint(item, $event, '{{waterCategories_listinString}}')" class="btn btnLarge" style="width:300px;">{% blocktrans %}Print your results!{% endblocktrans %}</button>
            <!--<p>{% blocktrans %}You can now switch off the Paccotest{% endblocktrans %}</p>-->
        <button ng-click="shutdownAnswer.doShutdownClick(item, $event)" class="btn btnLarge" style="width:300px;">{% trans "Shutdown Paccotest" %}</button>

    </div>
{% endblock %}

app/paccotest/templates/paccotest/done.html
DONE!

app/paccotest/templates/paccotest/form.html
{% extends "paccotest/base.html" %}
{% load i18n %}

{% block head %}
{{ wizard.form.media }}
{% endblock %}

{% block content %}
<p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
<form action="" method="post">{% csrf_token %}
<table>
{{ wizard.management_form }}
{% if wizard.form.forms %}
    {{ wizard.form.management_form }}
    {% for form in wizard.form.forms %}
        {{ form }}
    {% endfor %}
{% else %}
    {{ wizard.form }}
{% endif %}
</table>
{% if wizard.steps.prev %}
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">{% trans "first step" %}</button>
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">{% trans "prev step" %}</button>
{% endif %}
<input type="submit" value="{% trans "submit" %}"/>
</form>
{% endblock %}

app/paccotest/templates/paccotest/gpsPositionForm.html
{% extends "paccotest/base.html" %}

{% load i18n %}
{% block content %}
    <div ng-controller="PositionController">

        <h1>{% trans "GPS" %}</h1>
        <br />
        <br />
         <a href ng-click="myData.doClick(item, $event)" class="btn btnA">{% trans "Measure" %}</a>

        <div ng-show="myData.fromServer != null">
            <ul class="resultsGPS">
                <li>{% trans "latitude" %} : <span class="resultdisplayA">{[{myData.fromServer.latitude}]}</span></li>
                <li>{% trans "longitude" %} : <span class="resultdisplayA">{[{myData.fromServer.longitude}]}</span></li>
                <li>{% trans "elevation" %} : <span class="resultdisplayA">{[{myData.fromServer.elevation}]}</span></li>
                <li>{% trans "utc" %} : <span class="resultdisplayA">{[{myData.fromServer.utc}]}</span></li>
            </ul>

            <!-- Filled by AngularJS on Ajax Request -->
            <form method="post" action="{% url 'paccotest:gpsPositionForm' %}">
                {% csrf_token %}
                {{ form }}
                <br /><br />
                <button type="submit" class="btn btnC btnLarge btnChangePage" value="{% trans 'submit' %}" name="{% trans 'submit' %}" style="">{% trans 'button-next' %}</button>
            </form>
        </div>

      </div>

{% endblock %}

app/paccotest/templates/paccotest/intro.html
{% extends "paccotest/base.html" %}

{% load i18n %}
{% block content %}
        <h1>{% trans "Intro" %}</h1>
        <br />
        <p>{% blocktrans %}Welcome to the Pacco-Test{% endblocktrans %}</p>
        <br />
        <br />
        <p><a class="btn btnLarge btnChangePage" href="{% url 'paccotest:gpsPositionForm' %}">{% trans "button-next" %}</a></p>
{% endblock %}

app/paccotest/templates/paccotest/opening.html
{% extends "paccotest/base.html" %}


{% block content %}
        <p  style="text-align:center;"><img src="/static/img/logo.png" /></p>
        <br />
        <p class="btnPar3" style="text-align:center;">
           <a class="btn btnChangePage" href="{% url 'paccotest:intro' lg='fr'  %}">Français</a>
           <a class="btn btnChangePage" href="{% url 'paccotest:intro' lg='nl' %}">Nederlands</a>
           <a class="btn btnChangePage" href="{% url 'paccotest:intro' lg='en' %}">English</a>
        </p>
{% endblock %}